### ISSUE TITLE
Add Coding Resource Finder project

### ISSUE THREAD

**Issue by Ngoakor12** [Dun-sin/react-open-source-projects#13]
Hey :)

Coding Resources Finder - An easier way to find coding related topics and projects on the ACN syllabus

[Live project link](https://coding-resource-finder.ngoako.dev/)
[Repo project link](https://github.com/Ngoakor12/coding-resource-finder)

**Comment by Dun-sin** [comment]
Awesome, your project passes the requirements, feel free to make a PR🔥👌🏽
