### ISSUE TITLE
BioDrop would like to be listed

### ISSUE THREAD

**Issue by eddiejaoude** [Dun-sin/react-open-source-projects#21]
Here is our GitHub repo https://github.com/EddieHubCommunity/BioDrop

**Comment by Dun-sin** [comment]
Want to create the PR yourself?

**Comment by akinpinkman** [comment]
I can if Eddie won't create.

**Comment by eddiejaoude** [comment]
I will let someone else add it

**Comment by Dun-sin** [comment]
@akinpinkman still want to?

**Comment by akinpinkman** [comment]
Sure

**Comment by Dun-sin** [comment]
okay then

**Comment by akinpinkman** [comment]
Could you check if everything is okay? #22
