### ISSUE TITLE
BioDrop should be removed from the list

### ISSUE THREAD

**Issue by malavshah9** [Dun-sin/react-open-source-projects#23]
BioDrop was archived on June 10, 2024 so It should be removed from this list as well. If this gets approval then I can raise a PR to remove it.
![image](https://github.com/Dun-sin/react-open-source-projects/assets/29724200/f9707805-89e0-4eec-9b3b-e88a8a0262f4)

**Comment by Dun-sin** [comment]
Good spot, totally sad about BioDrop 😞

Go for it
