### ISSUE TITLE
year-in-review 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [Dun-sin/react-open-source-projects#8]
An [archive](https://github.com/kaf-lamed-beyt/year-in-review)  that holds the "year in review" articles written by folks in the tech community to serve as a form of encouragement, inspiration or Ginger!

**Comment by Dun-sin** [comment]
Hello, thanks for raising an issue to add your project, but it doesn't reach the requirements for adding a project to this repo as stated in the contributing.md file.

Hence I'm closing this issue along side the pull request created with it

**Comment by kaf-lamed-beyt** [comment]
Oh! 

I thought the rule would be overlooked, since the project is sorta related to the experiences of people (yearly) in the tech community, and adding it here would give it more visibility so other folks can contribute too.

Apologies for creating the issue, and submitting a PR nonetheless.

**Comment by Dun-sin** [comment]
> Oh! 
> 
> I thought the rule would be overlooked, since the project is sorta related to the experiences of people (yearly) in the tech community, and adding it here would give it more visibility so other folks can contribute too.
> 
> Apologies for creating the issue, and submitting a PR nonetheless. 

There's a reason for the limit, I don't know what you mean by yearly, but nonetheless apologies accepted
